name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite (ajuste conforme necessário)
  workflow_dispatch:

jobs:
  build:
    name: Generate contribution snake animation
    runs-on: ubuntu-latest
    steps:
      # Gera o SVG do Snake
      - uses: Platane/snk@v3
        with:
          github_user_name: gunegrini
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg

      # Publica na branch output/
      - name: Push snake animation to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
